### ISSUE TITLE
Which software should I choose?

### ISSUE THREAD

**Issue by lyangfan** [AlgorithmicBotany/vlab#1]
I would like to synthesize some images to test my phenotype measurement algorithm. I need to adjust certain parameters such as growth rate, color, leaf angle, etc., to generate a large number of images. Which software from your laboratory should I use to achieve this?

Thanks!

Yangfan
2023.6.6

**Comment by mikcieslak** [comment]
Thank you for asking this question. It is not easy to give you an informative reply here. I suggest you check out the vlab forum on the FSPM Discourse server: https://fspm.discourse.group. There is a new post there (from today!) that should help you: https://fspm.discourse.group/t/introduction-to-vlab-features-distribution-and-learning-resources/210
